// DESTPEC Bâtiment — bilingual content (FR primary, EN expat audience).
// Tone: FR = artisanal pride, parole de compagnon. EN = direct, no-surprises
// pragmatism. Not literal translations.

export const LANGS = ['fr'];

const PHONE_FR = '06 46 22 79 93';
const PHONE_INT = '+33 6 46 22 79 93';

export const content = {
  fr: {
    code: 'fr',
    siteName: 'DESTPEC Bâtiment',
    contact: {
      phoneDisplay: PHONE_FR,
      phoneHref: PHONE_INT.replace(/\s/g, ''),
      email: 'contact@destpec-batiment.fr',
      address: '14 rue des Artisans, 90000 Belfort',
      hours: [
        ['Lundi – vendredi', '8 h – 18 h 30'],
        ['Samedi', '9 h – 12 h'],
      ],
      siret: 'SIRET 512 847 693 00027 · RCS Belfort',
    },
    nav: [
      { key: 'home', label: 'Accueil' },
      { key: 'prestations', label: 'Prestations' },
      { key: 'realisations', label: 'Réalisations' },
      { key: 'apropos', label: 'À propos' },
      { key: 'contact', label: 'Contact' },
    ],
    navCta: 'Devis gratuit',
    navOpen: 'Ouvrir le menu',
    navClose: 'Fermer le menu',
    langSwitchLabel: 'English version',

    meta: {
      home: {
        title: 'DESTPEC Bâtiment · Construction & rénovation à Belfort (90)',
        desc: 'Entreprise générale du bâtiment à Belfort : construction de maisons, rénovation, extension, isolation. Devis gratuit sous 48 h, garantie décennale, certifié RGE.',
      },
      prestations: {
        title: 'Prestations · Maçonnerie, construction, rénovation, isolation',
        desc: 'Gros œuvre, construction de maisons clé en main, rénovation complète, extensions et isolation extérieure dans le Territoire de Belfort et le Nord Franche-Comté. Prix fermes, plannings contractuels.',
      },
      realisations: {
        title: 'Réalisations · Chantiers avant / après à Belfort',
        desc: 'Maisons construites, longères rénovées, extensions et isolations autour de Belfort, Montbéliard et Héricourt. Photos avant / après, durées et budgets réels.',
      },
      devis: {
        title: 'Devis gratuit · Estimation en ligne en 5 étapes',
        desc: 'Décrivez votre projet en 5 étapes, obtenez une fourchette de prix immédiate et une estimation de vos aides (MaPrimeRénov’, CEE). Réponse sous 48 h.',
      },
      apropos: {
        title: 'À propos · Une entreprise de compagnons depuis 2008',
        desc: 'DESTPEC Bâtiment, entreprise générale fondée en 2008 à Belfort. 240 chantiers livrés, équipes en interne, certifiée RGE Qualibat.',
      },
      contact: {
        title: 'Contact · Parlez-nous de votre projet',
        desc: 'Appelez DESTPEC Bâtiment au 06 46 22 79 93 ou écrivez-nous. Dépôt à Belfort, interventions à 30 km à la ronde.',
      },
    },

    common: {
      ctaDevis: 'Demander un devis gratuit',
      ctaCall: `Appeler le ${PHONE_FR}`,
      ctaProjects: 'Voir nos réalisations',
      ctaServices: 'Découvrir nos prestations',
      ctaAbout: 'Découvrir l’entreprise',
      ctaContact: 'Nous contacter',
      readMore: 'Voir le chantier',
      before: 'Avant',
      after: 'Après',
      location: 'Lieu',
      year: 'Année',
      duration: 'Durée',
      surface: 'Surface',
      allRights: 'Tous droits réservés.',
      footerTagline: 'Entreprise générale du bâtiment à Belfort. Construction, rénovation, extension, isolation dans le Territoire de Belfort et le Nord Franche-Comté.',
      footerNavTitle: 'Le site',
      footerContactTitle: 'Nous trouver',
      footerCertsTitle: 'Garanties',
      certs: ['Certifié RGE Qualibat', 'Garantie décennale AXA', 'Devis détaillé sous 48 h', 'Interlocuteur unique'],
      sliderLabel: 'Comparer avant et après',
      sliderHint: 'Glissez pour comparer',
    },

    home: {
      hero: {
        marker: 'Avant',
        title: 'On vous rend la maison <em>finie</em>.',
        sub: 'Construction, rénovation, extension et isolation à Belfort. Un interlocuteur, un planning contractuel, un budget tenu.',
        cta: 'Demander un devis gratuit',
        callPrefix: 'ou appelez le',
        seqAlt: 'La même maison, du crépi fissuré sous ciel gris jusqu’à la façade refaite en plein soleil.',
        beat2: {
          title: 'Enduit, toiture, menuiseries, <em>isolation</em>.',
          body: 'Un seul chantier, mené par les mêmes compagnons, du premier coup de pioche à la dernière plinthe. Vous ne coordonnez personne : c’est notre travail.',
        },
        beat3: {
          marker: 'Après',
          title: 'Le chantier se ferme, <em>votre histoire commence</em>.',
          body: 'Livré dans les délais, site impeccable. Ce qu’on écrit, on le construit.',
          cta: 'Estimer mon projet',
        },
      },
      price: {
        title: 'Combien ça coûte, <em>vraiment</em>.',
        lead: 'Les fourchettes que nous appliquons réellement, avant tout rendez-vous. Bougez le curseur : le chiffre bouge avec vous.',
        typeLabel: 'Votre projet',
        surfaceLabel: 'Surface concernée',
        aidsQuestion: 'Revenus du foyer',
        aidsHint: 'Détermine MaPrimeRénov’ et la prime CEE.',
        rangeLabel: 'Fourchette indicative, TTC',
        perM2Label: 'Prix au m²',
        aidsLabel: 'Aides déduites',
        netLabel: 'Reste à votre charge',
        noAidsLabel: 'Pas d’aide énergie sur ce type de projet',
        note: 'Fourchette issue de nos chantiers 2025-2026 dans le Territoire de Belfort. Le devis, lui, est ferme et détaillé poste par poste.',
        cta: 'Affiner et recevoir le devis',
      },

      intro: {
        title: 'L’entreprise qu’on recommande <em>à ses voisins</em>.',
        body: '240 maisons construites ou rénovées en dix-huit ans, et pas un chantier abandonné. Nos équipes sont en interne, nos prix sont fermes, et nos clients habitent à moins de 30 km. Quand un chantier se passe bien, tout le village le sait. C’est comme ça qu’on travaille.',
      },
      services: {
        title: 'Du gros œuvre aux finitions, <em>une seule entreprise</em>.',
        sub: 'Faites défiler : la maison se monte au fil de nos cinq métiers.',
        items: [
          {
            n: '01',
            title: 'Maçonnerie & gros œuvre',
            body: 'Fondations, dalles, élévation des murs, ouvertures de baies. La base solide de tout le reste, coulée et dressée par nos propres maçons.',
            stage: 'foundation',
          },
          {
            n: '02',
            title: 'Construction de maisons',
            body: 'Des maisons individuelles clé en main, du plan d’architecte à la remise des clés. Prix et délai écrits dans le contrat, pas sur un coin de table.',
            stage: 'frame',
          },
          {
            n: '03',
            title: 'Rénovation & transformation',
            body: 'Rénovation complète ou partielle de maisons anciennes : structure, toiture, réseaux, pièces de vie. On respecte la maison, on change tout le reste.',
            stage: 'walls',
          },
          {
            n: '04',
            title: 'Extension & surélévation',
            body: 'Gagner 30 ou 60 m² sans déménager : extensions bois ou maçonnées, surélévations de pavillons, raccordements propres à l’existant.',
            stage: 'roof',
          },
          {
            n: '05',
            title: 'Isolation & énergie',
            body: 'Isolation par l’extérieur, combles, menuiseries performantes. Chantiers éligibles MaPrimeRénov’ et CEE, dossiers montés avec vous.',
            stage: 'windows',
          },
        ],
      },
      stats: {
        title: 'Des chiffres, pas des slogans',
        items: [
          { value: 240, suffix: '+', label: 'chantiers livrés depuis 2008' },
          { value: 18, suffix: '', label: 'ans de métier à Belfort' },
          { value: 10, suffix: ' ans', label: 'de garantie décennale AXA' },
        ],
      },
      featured: {
        title: 'Des chantiers <em>près de chez vous</em>.',
        sub: 'Chaque projet est documenté avant / après, avec sa durée réelle.',
        more: 'Toutes les réalisations',
      },
      method: {
        title: 'Une méthode, <em>pas des promesses</em>.',
        img: 'photo-1454165804606-c3d57bc86b40',
        imgAlt: 'Plans de maison annotés à la main lors d’une étude de devis',
        items: [
          {
            icon: 'user',
            title: 'Un interlocuteur unique',
            body: 'Un conducteur de travaux attitré, joignable sur son mobile, du premier devis à la remise des clés.',
          },
          {
            icon: 'calendar',
            title: 'Un planning contractuel',
            body: 'Dates d’ouverture et de fin de chantier écrites dans le devis, avec pénalités de retard à notre charge.',
          },
          {
            icon: 'euro',
            title: 'Un budget tenu',
            body: 'Prix ferme, détaillé poste par poste. Aucun avenant sans votre accord écrit, jamais de surprise en fin de chantier.',
          },
          {
            icon: 'shield',
            title: 'Un chantier propre',
            body: 'Protection des lieux, tri des déchets, balayage chaque soir. Votre voisinage vous dira merci.',
          },
        ],
      },
      reviews: {
        title: 'Ce qu’en disent <em>les clients</em>.',
        sub: 'Avis vérifiés, chantiers visitables sur demande.',
        items: [
          {
            text: 'Une équipe sérieuse, du premier coup de pioche au dernier coup de pinceau. Le planning annoncé a été tenu au jour près, et le chantier était propre chaque soir.',
            name: 'Marie & Laurent P.',
            place: 'Belfort',
            job: 'Rénovation complète d’une maison de ville',
          },
          {
            text: 'Devis clair, prix respecté, et un chef de chantier qui décroche son téléphone. L’extension a été livrée avant la date prévue. On recommande sans réserve.',
            name: 'Karim B.',
            place: 'Montbéliard',
            job: 'Extension bois de 40 m²',
          },
          {
            text: 'Notre longère est méconnaissable, dans le bon sens. Ils ont gardé les pierres et les poutres, et tout refait derrière. Le budget n’a pas bougé d’un euro.',
            name: 'Sophie & Marc D.',
            place: 'Héricourt',
            job: 'Rénovation d’une longère du XVIIIe',
          },
        ],
      },
      aids: {
        title: 'Vos travaux, <em>vos aides</em>.',
        body: 'Isolation et rénovation énergétique ouvrent droit à plusieurs dispositifs. Nous sommes certifiés RGE, condition indispensable, et nous montons les dossiers avec vous.',
        items: [
          { name: 'MaPrimeRénov’', desc: 'Jusqu’à 75 €/m² d’isolation extérieure selon vos revenus' },
          { name: 'Prime énergie CEE', desc: 'Versée par les fournisseurs d’énergie, cumulable' },
          { name: 'TVA à 5,5 %', desc: 'Sur les travaux de performance énergétique' },
          { name: 'Éco-PTZ', desc: 'Jusqu’à 50 000 € à taux zéro pour financer le reste' },
        ],
        cta: 'Estimer mes aides en 2 minutes',
      },
      area: {
        title: 'À 30 km <em>autour de Belfort</em>.',
        body: 'Nous restons volontairement proches de nos chantiers : un chef de chantier ne peut pas être partout. Votre commune n’apparaît pas ? Appelez, si c’est faisable bien, on vient.',
        img: 'photo-1500382017468-9049fed747ef',
        imgAlt: 'La Trouée de Belfort au coucher du soleil, entre Vosges et Jura',
        towns: ['Belfort', 'Danjoutin', 'Valdoie', 'Offemont', 'Essert', 'Bavilliers', 'Andelnans', 'Chèvremont', 'Montbéliard', 'Héricourt', 'Delle', 'Giromagny'],
      },
    },

    prestations: {
      head: {
        title: 'Cinq métiers, <em>une seule signature</em>.',
        sub: 'Tout est fait par nos équipes ou sous notre direction directe : pas de sous-traitance en cascade, pas d’intermédiaire. Ce que nous signons, nous le faisons.',
        img: 'photo-1504307651254-35680f356dfd',
        imgAlt: 'Maçons DESTPEC sur un ferraillage de dalle, gilets orange',
      },
      items: [
        {
          id: 'maconnerie',
          icon: 'trowel',
          title: 'Maçonnerie & gros œuvre',
          lead: 'Le squelette de votre maison, coulé et monté par nos maçons en CDI.',
          body: 'Terrassement coordonné, fondations, dalles béton, élévation en parpaing ou brique, ouvertures de baies dans l’existant, petites démolitions. Chaque étape est contrôlée et photographiée avant d’être masquée.',
          list: ['Fondations et radier', 'Dalles et planchers béton', 'Élévation parpaing / brique', 'Ouvertures de murs porteurs', 'Reprise en sous-œuvre'],
          price: 'Sur étude structurelle, devis sous 5 jours',
          img: 'photo-1541888946425-d81bb19240f5',
          imgAlt: 'Équipe de maçons sur une dalle béton en cours de ferraillage',
        },
        {
          id: 'construction',
          icon: 'house',
          title: 'Construction de maisons neuves',
          lead: 'Clé en main, du plan à la remise des clés, avec prix et délai contractuels.',
          body: 'Vous apportez un terrain, avec ou sans plan. Nous coordonnons l’architecte si besoin, déposons le permis, construisons, et livrons une maison prête à vivre. Contrat de construction CCMI, garanties légales complètes.',
          list: ['Étude de faisabilité et implantation', 'Dépôt de permis de construire', 'Contrat CCMI à prix ferme', 'Suivi de chantier hebdomadaire', 'Garanties : parfait achèvement, biennale, décennale'],
          price: 'À partir de 1 750 €/m² habitables',
          img: 'photo-1600585154340-be6161a56a0c',
          imgAlt: 'Maison contemporaine à ossature mixte livrée au crépuscule',
        },
        {
          id: 'renovation',
          icon: 'roller',
          title: 'Rénovation & transformation',
          lead: 'On garde l’âme de la maison, on refait tout le reste.',
          body: 'Rénovation complète ou par lots : dépose, structure, toiture, réseaux électriques et plomberie, plâtrerie, cuisine, salles d’eau, finitions. Habité ou vide, le chantier est phasé pour limiter la gêne.',
          list: ['Diagnostic et relevés précis', 'Réfection électrique aux normes', 'Plomberie, cuisine, salles d’eau', 'Plâtrerie, sols, peinture', 'Coordination de tous les corps d’état'],
          price: 'De 600 à 1 500 €/m² selon l’ampleur',
          img: 'photo-1502005229762-cf1b2da7c5d6',
          imgAlt: 'Cage d’escalier rénovée, marches en chêne et garde-corps acier',
        },
        {
          id: 'extension',
          icon: 'expand',
          title: 'Extension & surélévation',
          lead: 'Des mètres carrés en plus, sans déménager ni défigurer la maison.',
          body: 'Extensions bois ou maçonnées, vérandas habitables, surélévations de pavillons. Nous gérons la déclaration préalable ou le permis, les raccordements à l’existant, et l’étanchéité de la jonction, point critique du genre.',
          list: ['Étude de faisabilité et PLU', 'Ossature bois ou maçonnerie', 'Surélévation avec reprise de toiture', 'Raccordement réseaux à l’existant', 'Finitions assorties à la maison'],
          price: 'De 1 400 à 2 600 €/m² créés',
          img: 'photo-1600047509807-ba8f99d2cdde',
          imgAlt: 'Pavillon agrandi d’un volume contemporain en panneaux cuivrés',
        },
        {
          id: 'isolation',
          icon: 'leaf',
          title: 'Isolation & performance énergétique',
          lead: 'Une maison qui tient la chaleur, des factures qui fondent.',
          body: 'Isolation thermique par l’extérieur avec ravalement, isolation des combles, toiture, menuiseries double ou triple vitrage, VMC. Audit thermique d’entrée de chantier, attestation de fin de travaux pour vos aides.',
          list: ['Audit et priorisation des postes', 'ITE avec ravalement de façade', 'Isolation des combles et toiture', 'Menuiseries performantes', 'Dossiers MaPrimeRénov’ et CEE inclus'],
          price: 'De 90 à 160 €/m² de paroi traitée',
          img: 'photo-1632759145351-1d592919f522',
          imgAlt: 'Couvreur DESTPEC sur une toiture en cours d’isolation',
        },
      ],
      process: {
        title: 'Comment se passe <em>un chantier DESTPEC</em> ?',
        steps: [
          { n: '1', title: 'Visite technique', body: 'Gratuite, chez vous, avec relevés et photos. 45 minutes.' },
          { n: '2', title: 'Devis détaillé', body: 'Poste par poste, prix ferme, sous 48 h à 5 jours selon complexité.' },
          { n: '3', title: 'Planning signé', body: 'Dates de début et de fin écrites, pénalités de retard à notre charge.' },
          { n: '4', title: 'Chantier suivi', body: 'Point photo chaque semaine, conducteur de travaux joignable.' },
          { n: '5', title: 'Réception & garanties', body: 'Visite de réception contradictoire, garantie décennale AXA.' },
        ],
      },
    },

    realisations: {
      head: {
        title: 'Le travail parle <em>mieux que nous</em>.',
        sub: 'Sept chantiers récents, documentés avant / après, avec leur durée réelle. Glissez le curseur sur les photos pour comparer.',
      },
      filterLabel: 'Filtrer les chantiers par type',
      resultNounOne: 'chantier affiché',
      resultNoun: 'chantiers affichés',
      emptyState: 'Aucun chantier dans cette catégorie pour le moment. Choisissez « Tous » pour revoir l’ensemble.',
      filters: [
        { key: 'all', label: 'Tous' },
        { key: 'construction', label: 'Construction' },
        { key: 'renovation', label: 'Rénovation' },
        { key: 'extension', label: 'Extension' },
        { key: 'isolation', label: 'Isolation' },
      ],
      items: [
        {
          id: 'valdoie',
          cat: 'construction',
          title: 'Maison contemporaine de 165 m²',
          place: 'Valdoie',
          year: '2025',
          duration: '11 mois',
          surface: '165 m²',
          body: 'Terrain nu en entrée, maison livrée clé en main : ossature mixte, toiture zinc, menuiseries aluminium, jardin engazonné. Livrée avec trois semaines d’avance.',
          before: { id: 'photo-1500382017468-9049fed747ef', alt: 'Le terrain nu avant construction, champ au soleil couchant' },
          after: { id: 'photo-1600585154340-be6161a56a0c', alt: 'La maison contemporaine terminée au crépuscule' },
        },
        {
          id: 'hericourt',
          cat: 'renovation',
          title: 'Rénovation complète d’une longère',
          place: 'Héricourt',
          year: '2024',
          duration: '7 mois',
          surface: '210 m²',
          body: 'Pierres et poutres conservées, tout le reste refait : réseaux, planchers, isolation par l’intérieur en fibre de bois, cuisine et trois salles d’eau.',
          before: { id: 'photo-1522708323590-d24dbb6b0267', alt: 'Le séjour avant travaux, mobilier vieilli et murs ternes' },
          after: { id: 'photo-1616486338812-3dadae4b4ace', alt: 'Le séjour après rénovation, lumineux et ouvert' },
        },
        {
          id: 'belfort',
          cat: 'extension',
          title: 'Extension bois de 45 m²',
          place: 'Belfort',
          year: '2025',
          duration: '4 mois',
          surface: '45 m²',
          body: 'Un volume contemporain accolé à un pavillon des années 80 : ossature bois, bardage, grande baie coulissante. Raccordement invisible à l’existant.',
          before: { id: 'photo-1570129477492-45c003edd2be', alt: 'Le pavillon avant extension, façade d’origine' },
          after: { id: 'photo-1600047509807-ba8f99d2cdde', alt: 'La maison après extension, volume contemporain en panneaux cuivrés' },
        },
        {
          id: 'danjoutin',
          cat: 'isolation',
          title: 'ITE et ravalement complet',
          place: 'Danjoutin',
          year: '2024',
          duration: '3 mois',
          surface: '140 m² de façade',
          body: 'Isolation par l’extérieur en 16 cm, ravalement minéral, menuiseries remplacées. Consommation de chauffage divisée par deux, 9 800 € d’aides obtenues.',
          before: { id: 'photo-1605146769289-440113cc3d00', alt: 'La façade avant travaux, crépi fatigué' },
          after: { id: 'photo-1523217582562-09d0def993a6', alt: 'La façade après ITE et ravalement, lignes nettes' },
        },
        {
          id: 'montbeliard',
          cat: 'renovation',
          title: 'Maison de ville rénovée',
          place: 'Montbéliard',
          year: '2023',
          duration: '5 mois',
          surface: '120 m²',
          body: 'Rénovation lourde en site occupé, phasée pièce par pièce : électricité, plomberie, plâtrerie, sols et peinture. Les propriétaires ne sont jamais partis.',
          before: { id: 'photo-1493809842364-78817add7ffb', alt: 'La pièce de vie avant rénovation' },
          after: { id: 'photo-1600607687920-4e2a09cf159d', alt: 'La salle à manger après rénovation, mur en marbre et verrière' },
        },
        {
          id: 'giromagny',
          cat: 'renovation',
          title: 'Cuisine et pièce de vie',
          place: 'Giromagny',
          year: '2025',
          duration: '6 semaines',
          surface: '48 m²',
          body: 'Mur de refend ouvert avec IPN, cuisine repensée autour d’un îlot de 2,80 m, éclairage intégré. La pièce est devenue le cœur de la maison.',
          before: { id: 'photo-1556911220-bff31c812dba', alt: 'La cuisine fermée avant ouverture du mur' },
          after: { id: 'photo-1600585152220-90363fe7e115', alt: 'La cuisine ouverte après travaux, îlot et suspensions' },
        },
        {
          id: 'delle',
          cat: 'construction',
          title: 'Maison familiale de 140 m²',
          place: 'Delle',
          year: '2024',
          duration: '10 mois',
          surface: '140 m²',
          body: 'De la dalle à la remise des clés en dix mois : maison traditionnelle à étage, toiture tuiles, garage attenant. Réception sans aucune réserve.',
          before: { id: 'photo-1508450859948-4e04fabaa4ea', alt: 'L’élévation des murs en cours, structure béton' },
          after: { id: 'photo-1568605114967-8130f3a36994', alt: 'La maison terminée au crépuscule, fenêtres allumées' },
        },
      ],
      cta: {
        title: 'Votre projet mérite <em>la même exigence</em>.',
        body: 'Visite technique gratuite, devis détaillé sous 48 h.',
      },
    },

    devis: {
      head: {
        title: 'Votre devis commence <em>ici</em>.',
        sub: 'Cinq étapes, trois minutes. Une fourchette de prix s’affiche au fil de vos réponses, puis un compagnon vous rappelle pour la visite technique.',
      },
      trust: ['Gratuit et sans engagement', 'Réponse sous 48 h ouvrées', 'Vos photos restent privées'],
      steps: [
        { id: 'type', label: 'Projet' },
        { id: 'details', label: 'Détails' },
        { id: 'aides', label: 'Estimation' },
        { id: 'contact', label: 'Coordonnées' },
        { id: 'rappel', label: 'Rappel' },
      ],
      nav: { prev: 'Retour', next: 'Continuer', submit: 'Envoyer ma demande' },
      estimate: {
        title: 'Estimation en direct',
        empty: 'Choisissez un type de projet pour démarrer l’estimation.',
        range: 'Fourchette indicative',
        vat: 'TTC, finitions standard comprises',
        disclaimer: 'Estimation indicative à partir de nos chantiers récents. Le prix ferme est établi après visite technique, sans engagement.',
        surfaceLabel: 'Surface estimée',
        perM2: 'soit {price} €/m²',
      },
      step1: {
        title: 'Quel est votre projet ?',
        sub: 'Une seule réponse possible. Vous pourrez préciser à l’étape suivante.',
        types: [
          { id: 'construction', icon: 'house', title: 'Maison neuve', desc: 'Construire sur votre terrain, clé en main' },
          { id: 'renovation', icon: 'roller', title: 'Rénovation', desc: 'Transformer ou rénover l’existant' },
          { id: 'extension', icon: 'expand', title: 'Extension', desc: 'Agrandir, surélever, ajouter un volume' },
          { id: 'isolation', icon: 'leaf', title: 'Isolation', desc: 'Murs, toiture, combles, menuiseries' },
          { id: 'amenagement', icon: 'layout', title: 'Aménagement', desc: 'Combles, garage, sous-sol à vivre' },
        ],
      },
      step2: {
        title: 'Parlez-nous du projet',
        sub: 'Ces réponses affinent la fourchette affichée à droite.',
        surface: 'Surface concernée',
        surfaceUnit: 'm²',
        delay: 'Quand souhaitez-vous démarrer ?',
        delays: [
          { id: 'asap', label: 'Dès que possible' },
          { id: '3-6', label: 'Dans 3 à 6 mois' },
          { id: '6-12', label: 'Dans 6 à 12 mois' },
          { id: 'info', label: 'Je me renseigne pour l’instant' },
        ],
        perType: {
          construction: {
            field: 'terrain', label: 'Où en êtes-vous du terrain ?',
            options: [
              { id: 'owned', label: 'Terrain signé' },
              { id: 'pending', label: 'Compromis en cours' },
              { id: 'searching', label: 'Je cherche encore' },
            ],
          },
          renovation: {
            field: 'ampleur', label: 'Quelle ampleur ?',
            options: [
              { id: 'partial', label: 'Rénovation partielle (quelques pièces)' },
              { id: 'full', label: 'Rénovation complète (structure, réseaux, finitions)' },
            ],
            energy: 'Inclure des travaux d’isolation ou de chauffage',
          },
          extension: {
            field: 'kind', label: 'Quel type d’agrandissement ?',
            options: [
              { id: 'wood', label: 'Extension bois' },
              { id: 'masonry', label: 'Extension maçonnée' },
              { id: 'raise', label: 'Surélévation' },
            ],
          },
          isolation: {
            field: 'postes', label: 'Quels postes isoler ?',
            multi: true,
            options: [
              { id: 'walls', label: 'Murs par l’extérieur' },
              { id: 'roof', label: 'Toiture' },
              { id: 'attic', label: 'Combles' },
              { id: 'windows', label: 'Menuiseries' },
            ],
          },
          amenagement: {
            field: 'space', label: 'Quel espace transformer ?',
            options: [
              { id: 'attic', label: 'Combles perdus' },
              { id: 'garage', label: 'Garage' },
              { id: 'basement', label: 'Sous-sol' },
              { id: 'barn', label: 'Dépendance ou grange' },
            ],
          },
        },
      },
      step3: {
        title: 'Votre estimation et vos aides',
        sub: 'La fourchette est recalculée à chaque réponse. Les aides dépendent de vos revenus : sélectionnez votre foyer pour les estimer.',
        bracketLabel: 'Revenus du foyer (avis d’imposition)',
        brackets: [
          { id: 'bleu', label: 'Très modestes', hint: 'couleur bleue sur le simulateur Anah' },
          { id: 'jaune', label: 'Modestes', hint: 'couleur jaune' },
          { id: 'violet', label: 'Intermédiaires', hint: 'couleur violette' },
          { id: 'rose', label: 'Supérieurs', hint: 'couleur rose' },
          { id: 'unknown', label: 'Je ne sais pas / non concerné' },
        ],
        aidsTitle: 'Aides estimées',
        noAids: 'Votre projet n’ouvre pas droit aux aides énergie. La TVA à 10 % s’applique en rénovation.',
        notEligible: 'Avec ces revenus, seuls la prime CEE et la TVA réduite restent accessibles.',
        unknown: 'Répondez à la question des revenus pour estimer vos aides.',
        lines: { maprimerenov: 'MaPrimeRénov’', cee: 'Prime énergie CEE', tva: 'TVA réduite à 5,5 %', tvaNote: 'appliquée au devis' },
        totalAids: 'Total des aides estimées',
        net: 'Reste estimé après aides',
        disclaimer: 'Montants indicatifs 2026, sous réserve d’éligibilité confirmée sur <a href="https://france-renov.gouv.fr" target="_blank" rel="noopener">france-renov.gouv.fr</a>. Certifié RGE : condition d’accès aux aides, déjà remplie.',
      },
      step4: {
        title: 'Où vous joindre ?',
        sub: 'Un conducteur de travaux vous rappelle. Pas de démarchage, pas de revente de données.',
        name: 'Nom et prénom',
        namePh: 'Ex. Claire Martin',
        email: 'E-mail',
        emailPh: 'claire@exemple.fr',
        phone: 'Téléphone',
        phonePh: '06 12 34 56 78',
        zip: 'Code postal du chantier',
        zipPh: '90000',
        message: 'Précisions utiles (facultatif)',
        messagePh: 'Accès au terrain, contraintes, historique de la maison…',
        photos: 'Photos du projet (facultatif)',
        photosHint: 'Jusqu’à 6 photos, 8 Mo chacune. Façades, pièces, plans : tout aide au premier chiffrage.',
        photosAdd: 'Ajouter des photos',
        consent: 'J’accepte que DESTPEC me recontacte au sujet de ma demande.',
        errors: {
          name: 'Indiquez votre nom pour que l’on sache à qui parler.',
          email: 'Cet e-mail semble incomplet.',
          phone: 'Un numéro à 10 chiffres nous évite de nous tromper.',
          zip: 'Le code postal contient 5 chiffres.',
          consent: 'Sans votre accord, nous ne pouvons pas vous rappeler.',
        },
      },
      step5: {
        title: 'Quand vous rappelle-t-on ?',
        sub: 'Choisissez un créneau, ou envoyez sans rappel : nous répondons par écrit sous 48 h ouvrées.',
        dayLabel: 'Jour préféré',
        slotLabel: 'Créneau',
        slots: ['8 h 30 – 10 h', '10 h – 11 h 30', '14 h – 15 h 30', '16 h – 17 h 30'],
        noCall: 'Pas besoin de rappel, un e-mail suffit',
        weekdaysShort: ['lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.', 'dim.'],
        monthsShort: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'],
      },
      confirm: {
        badge: 'Demande envoyée',
        title: 'C’est noté, {name}.',
        body: 'Votre demande est enregistrée sous la référence ci-dessous. Un conducteur de travaux vous recontacte {when}.',
        whenCall: 'au créneau choisi',
        whenMail: 'par écrit sous 48 h ouvrées',
        refLabel: 'Référence de votre demande',
        recap: 'Votre projet en résumé',
        next: 'La suite',
        nextItems: [
          { title: 'Prise de contact', body: 'Vérification des accès et des premières contraintes, 10 minutes au téléphone.' },
          { title: 'Visite technique', body: 'Gratuite, chez vous, avec relevés et photos. 45 minutes.' },
          { title: 'Devis détaillé', body: 'Poste par poste, prix ferme, sous 48 h à 5 jours selon complexité.' },
        ],
        backHome: 'Retour à l’accueil',
        newRequest: 'Faire une autre demande',
      },
      progress: 'Étape {n} sur {total}',
      required: 'Champ requis',
    },

    apropos: {
      hero: {
        title: 'Des compagnons, <em>pas des commerciaux</em>.',
        sub: 'DESTPEC est née en 2008 d’un constat simple : trop de chantiers mal suivis, trop de promesses en l’air. Dix-huit ans plus tard, nos clients nous prêtent leurs clés. C’est la plus belle des mesures de confiance.',
        img: 'photo-1541888946425-d81bb19240f5',
        imgAlt: 'L’équipe DESTPEC réunie sur une dalle en début de chantier',
      },
      story: {
        title: 'L’histoire',
        body: [
          'Aziz Amellah, compagnon maçon formé au Tour de France, reprend en 2008 la petite entreprise de son oncle à Belfort. Trois ouvriers, une camionnette, et une règle : on ne signe que ce qu’on peut faire soi-même.',
          'En 2014, l’entreprise devient DESTPEC et passe entreprise générale : maçons, charpentiers, couvreurs et plâtriers en interne, un bureau d’études pour le reste. En 2019, certification RGE Qualibat, et le carnet de commandes des rénovations énergétiques qui double.',
          'Aujourd’hui : 22 salariés, 240 chantiers livrés, et toujours la même règle. Quand nous manquons de compétence sur un poste, nous le disons et nous le coordonnons, au lieu de bricoler.',
        ],
      },
      values: {
        title: 'Ce qui ne change <em>jamais</em>.',
        items: [
          { icon: 'handshake', title: 'La parole donnée', body: 'Un prix signé est un prix tenu. Une date signée est une date tenue. Les imprévus se gèrent en transparence, jamais en fin de chantier.' },
          { icon: 'hammer', title: 'Le fait main', body: 'Nos compagnons sont en CDI, formés en interne, fiers de leur ouvrage. La qualité ne se sous-traite pas au plus offrant.' },
          { icon: 'eye', title: 'La transparence', body: 'Chaque étape masquée est photographiée avant d’être refermée. Vous voyez ce que contiennent vos murs.' },
        ],
      },
      team: {
        title: 'L’atelier, pas l’agence',
        body: 'Pas de force de vente : celui qui visite votre maison est celui qui dirigera le chantier. Le bureau tient dans le dépôt, au milieu des échafaudages et des big bags.',
        roles: ['Conducteurs de travaux (3)', 'Maçons (8)', 'Charpentiers & couvreurs (6)', 'Plâtriers & peintres (4)', 'Bureau d’études (2)'],
        img: 'photo-1621905251189-08b45d6a269e',
        imgAlt: 'Compagnon DESTPEC au travail sur un tableau électrique',
      },
      certs: {
        title: 'Garanties et certifications',
        items: [
          { name: 'RGE Qualibat', desc: 'Certification 5246, isolation et rénovation énergétique. Condition d’accès à MaPrimeRénov’.' },
          { name: 'Garantie décennale', desc: 'Assurés chez AXA, police n° 78 451 230. Attestation remise avant chaque ouverture de chantier.' },
          { name: 'Garantie de parfait achèvement', desc: 'Un an pour corriger tout défaut, pris en charge à 100 %.' },
          { name: 'CCMI', desc: 'Contrat de construction de maison individuelle avec garantie de livraison, plan et prix fermes.' },
        ],
      },
      cta: {
        title: 'Venez vérifier <em>par vous-même</em>.',
        body: 'Le café est au dépôt, les chantiers sont visitables, et les anciens clients répondent au téléphone.',
      },
    },

    contactPage: {
      head: {
        title: 'Parlez-nous, <em>on écoute</em>.',
        sub: 'Pour un projet de travaux, le devis en ligne est le chemin le plus rapide. Pour tout le reste, ce formulaire ou le téléphone.',
      },
      form: {
        title: 'Écrivez-nous',
        name: 'Nom et prénom',
        namePh: 'Ex. Claire Martin',
        email: 'E-mail',
        emailPh: 'claire@exemple.fr',
        phone: 'Téléphone (facultatif)',
        phonePh: '06 12 34 56 78',
        subject: 'Sujet',
        subjects: ['Question sur un chantier en cours', 'Garantie ou service après-vente', 'Partenariat ou fournisseur', 'Autre demande'],
        message: 'Votre message',
        messagePh: 'Dites-nous tout.',
        submit: 'Envoyer le message',
        sent: {
          title: 'Message bien reçu.',
          body: 'Nous répondons sous 48 h ouvrées. Pour un projet de travaux, le devis en ligne reste le plus rapide.',
          cta: 'Faire une demande de devis',
        },
        errors: {
          name: 'Indiquez votre nom.',
          email: 'Cet e-mail semble incomplet.',
          message: 'Quelques mots nous aideraient à bien router votre message.',
        },
      },
      aside: {
        title: 'Le dépôt',
        depotNote: 'Bureau et atelier. Chantiers dans un rayon de 30 km.',
        img: 'photo-1560518883-ce09059eeffa',
        imgAlt: 'Maquette de maison et trousseau de clés sur un bureau de chantier',
        devisNote: 'Un projet de travaux ?',
        devisBody: 'Le devis en ligne prend 3 minutes et affiche une estimation immédiate.',
      },
    },
  },
};
